CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_LOG=y
CONFIG_MPU6050_CUSTOM=y

CONFIG_GPIO=y
CONFIG_GPIO_BUZZER=y

CONFIG_LED_STRIP=y

# GC9A01 round TFT display
CONFIG_SPI=y
CONFIG_DISPLAY=y
CONFIG_MIPI_DBI=y
CONFIG_GC9X01X=y
